export const HOUSEHOLD_FINANCE_CATEGORIES = [
  "Moradia",
  "Alimentacao",
  "Mercado",
  "Transporte",
  "Saude",
  "Farmacia",
  "Educacao",
  "Lazer",
  "Assinaturas",
  "Energia",
  "Agua",
  "Gas",
  "Internet",
  "Manutencao",
  "Impostos",
  "Seguros",
  "Pets",
  "Roupas",
  "Salario",
  "Investimentos",
  "Reserva de emergencia",
] as const;
